### ISSUE TITLE
Annotation of Named Entities for NER Corpus

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/Data-Anonymizer#1]
AS A machine-learning-based application
I WANT TO have a list of properly annotated input within given entity classes
SO THAT I could use this as a basis to properly detect named entities based on new input

### Acceptance Criteria

- [x] buerokratt/Data-Anonymizer#2
- [x] buerokratt/Data-Anonymizer#4
- [x] buerokratt/Data-Anonymizer#12

- [x] buerokratt/Data-Anonymizer#3
- [x] buerokratt/Data-Anonymizer#5
- [x] buerokratt/Data-Anonymizer#6
- [x] buerokratt/Data-Anonymizer#7
- [x] buerokratt/Data-Anonymizer#8
- [x] buerokratt/Data-Anonymizer#9
- [x] buerokratt/Data-Anonymizer#10
- [x] buerokratt/Data-Anonymizer#11
- [x] buerokratt/Data-Anonymizer#13

**Comment by vmugra** [comment]
Uurida: Korpuste formaat, märgendamise notatsioon, listid

**Comment by tarstarkvara** [comment]
Code handed over to engineering side to refactor it production-ready and include in the API.
